# ===================================================================
#                     阿里云对象存储 (OSS) 配置
# ===================================================================
oss:
  bucket-name: img-zzy
  end-point: oss-cn-beijing.aliyuncs.com
  access-key: '**************'
  access-secret: '*****************'
