# ===================================================================
#                     AI 服务配置
# ===================================================================
spring:
  ai:
    dashscope:
      api-key: "*****"
      chat:
        options:
          model: "qwen3-max"