# ===================================================================
#                     AI 服务配置
# ===================================================================
spring:
  ai:
    dashscope:
      api-key: "sk-e08021e04d2b434a9e5316aaa9ec556a"
      chat:
        options:
          model: "qwen3-max"